### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by kodeine** [PrestaShopCorp/nestjs-geteventstore#44]
Hello,
So i am trying to use projections, i am new to events so i have a question on how would you approach this kind of concept.
I am subscribed to metrics report, i am getting metrics hourly basis. I need to use last metric + new one and do calculations and pass it as another event so a saga can listen and do updates.

How would i get last hour metric so i can compare with last + latest and how would i send it to another event so saga can listen. Please advise.

Thank you!

**Comment by Vinceveve** [comment]
Read this http://codeofrob.com/entries/evented-github-adventure---temporal-queries,-who-doesnt-trust-their-hardware.html and this https://www.eventstore.com/blog/playing-with-projections

Definitly projection inside eventstore is the solution : 
 - create a projection named `reporting` (target stream)
 - subscribe to reporting events
 - on each event update the state from last hour 
 - every x events `emit` a new event with some data in the state
 - use persistent subscription to get this new emited event 

TDD : https://github.com/Sergej-Popov/event-store-projection-testing
