### ISSUE TITLE
catchup subscriptions, lastCheckpoint usage in module.

### ISSUE THREAD

**Issue by kodeine** [PrestaShopCorp/nestjs-geteventstore#50]
So in the module how can i put the value of lastCheckpoint async way from cache or database.
Or is there a better way to set last checkpoint?

```
        subscriptions: {
          catchup: [{
            stream: '$ce-reports',
            lastCheckpoint: 350,
          }],
```

**Comment by jdharandas** [comment]
@Vinceveve

**Comment by Vinceveve** [comment]
you can use a persistent subscription and set the startFrom, that works great also.
For catchup lastCheckpoint is the only solution, but you use catchup mainly for bug fix. 
Or if you want to handle yourself the stream position and persistent subscription does not fit
