### ISSUE TITLE
property `metadata.correlation_id` is missing.

### ISSUE THREAD

**Issue by riseno** [PrestaShopCorp/nestjs-geteventstore#70]
Hi, i'm currently facing the issue that is missing the `correlation_id` in metadata of the event. 

this is occurred when i have a record created, and i want to apply another event to the record, then this happens. 

```
[Nest] 29200   - 07/19/2021, 10:32:39 AM   [WriteEventsPrepublishService] An instance of UserMigratedIdAttachedEvent has failed the validation:
 - property metadata.correlation_id has failed the following constraints: isNotEmpty, isString 
 +5ms
(node:29200) UnhandledPromiseRejectionWarning: Error: Invalid Event Exception
    at WriteEventBus.publishAll (/Users/ryanchan/repo/nestjs/user-service/node_modules/nestjs-geteventstore/dist/cqrs/write-event-bus.js:51:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async User.commit (/Users/ryanchan/repo/nestjs/user-service/node_modules/nestjs-geteventstore/dist/event-store/event-store-aggregate-root.js:13:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is the event dump. and also the source in metadata that is set to `null` somehow.

```
[
  UserMigratedIdAttachedEvent {
    data: {
      id: '2a22a00d-352d-432e-a370-f77aa2155c99',
      migratedId: 10011111
    },
    metadata: {
      specversion: 1,
      time: '2021-07-19T02:32:39.518Z',
      version: 1,
      correlation_id: null,
      type: 'Irenes-MBP.user-service.UserMigratedIdAttachedEvent.1',
      source: 'Irenes-MBPnull'
    },
    eventId: '4415ad5f-81c8-4f0b-8180-1c3673ab5a8b',
    eventType: 'UserMigratedIdAttachedEvent',
    eventStreamId: undefined,
    eventNumber: undefined,
    originalEventId: undefined,
    id: '2a22a00d-352d-432e-a370-f77aa2155c99',
    migratedId: 10011111
  }
]
```

**Comment by jdharandas** [comment]
Hello, 

You need to add ContextModule.register() to your app main-module if you want to be able to use the default prepublish service :

```
@Module({})
export class EventStoreHeroesModule {
  static register() {
    return {
      module: EventStoreHeroesModule,
      controllers: [HealthController, HeroesGameController],
      providers: [
        HeroRepository,
        ...CommandHandlers,
        ...EventHandlers,
        ...QueryHandlers,
        HeroesGameSagas,
      ],
      imports: [
        ...[ContextModule.register(), TerminusModule, LoggerModule.forRoot()],
        CqrsEventStoreModule.register(
          esConfig,
          { subscriptions, projections },
          eventBusConfig,
        ),
      ],
    };
  }
}
```

The default prepublish service will add some generic metadata in your events and will validate the data and metadata using class-validator. If you do not want to use that service, just pass a custom config for the write bus "prepare" and "validate" options:

```
export const eventBus = {
  write: { serviceName: 'my-service', validate: false, prepare: false },
};

```

Sorry we have not updated the Readme yet, version 3.x and 4.x have been developed to be used in internal projects and they are a WIP yet. We will work on documentation after summer.

**Comment by kodeine** [comment]
@jdharandas we are waiting for the readme as well. thank you for working on this repo.

**Comment by riseno** [comment]
@jdharandas 

Thanks for your reply about it, and it seems that the property is not boolean type by default, so setting `false` it will result in below's screenshot.

![Screenshot 2021-08-02 at 12 55 48 PM](https://user-images.githubusercontent.com/14790405/127806172-4b227ebe-7b8a-414e-8765-6e5c1c39344d.png)

Once i set to `null` it will do the trick you mentioned.

**Comment by kodeine** [comment]
@riseno can you please tell me how did u solve this? i tried to use null values but it still tries to validate.

**Comment by riseno** [comment]
> @riseno can you please tell me how did u solve this? i tried to use null values but it still tries to validate.

i gave up on this package. latest version have completely changed the configuration, poor documents and examples. 

and also gave up to use eventstore DB as well, switched back to mongodb for it.

**Comment by jdharandas** [comment]
@kodeine He has set it to null:

`export const eventBus = {
  write: { serviceName: 'my-service', validate: null, prepare: null },
};
`

**Comment by kodeine** [comment]
@jdharandas i tried with null values but it still validates and prepares. 

I want to disable this because correlation id is disappeared since the request comes from graphql and then goes to a micro-service kafka and then to eventstore.
